version: "3.8"

services:
   client:
      restart: always
      build:
         context: ./client
         dockerfile: Dockerfile
      container_name: react_nginx_frontend
      volumes:
         - ./client/node_modules:/app/node_modules
      # ports:
      #    - 3000:3000
      networks:
         - react_nginx-api

   nginx:
      restart: always
      depends_on:
         - client
      build:
         context: ./nginx
         dockerfile: Dockerfile
      ports:
         - 8086:80
      networks:
         - react_nginx-api

networks:
   react_nginx-api:
      driver: bridge