version: "3.8"

services:

   reactpractice:
      restart: always
      build:
         context: ./reactpractice
         dockerfile: Dockerfile
      container_name: library_mern_frontend
      volumes:
         - ./app/node_modules
         - ./reactpractice:/app
      # ports:
      #    - 3000:3000
      networks:
         - library-react-nginx

   nginx:
      restart: always
      depends_on:
         - reactpractice
      build:
         context: ./nginx
         dockerfile: Dockerfile
      ports:
         - 8080:80
      networks:
         - library-react-nginx

networks:
   library-react-nginx:
      driver: bridge