version: "3.8"

services:
   client:
      restart: always
      build:
         context: ./client
         dockerfile: Dockerfile
      container_name: reactjs_nginx_frontend
      volumes:
         - ./app/node_modules
         - ./client:/app
      # ports:
      #    - 3000:3000
      networks:
         - react_nginx_api

   nginx:
      restart: always
      depends_on:
         - client
      build:
         context: ./nginx
         dockerfile: Dockerfile
      ports:
         - 8080:80
      networks:
         - react_nginx_api

networks:
   react_nginx_api:
      driver: bridge